services:
  backend:
    build: ./backend
    container_name: backend_api
    ports:
      - "8000:8000"
    networks:
      - facturacion_net

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - facturacion_net

networks:
  facturacion_net:
    driver: bridge
