name: Checks on Tags

on:
  push:
    tags:
      - "v*"

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest httpx
          pip install -r Taller2_Facturacion/backend/requirements.txt
          pip install -r Taller2_Facturacion/frontend/requirements.txt

      - name: Run Ruff
        run: ruff check Taller2_Facturacion/ --fix --ignore E402

      - name: Run Pytest
        run: |
          cd Taller2_Facturacion/backend
          # Eliminamos archivos que puedan confundir a Pytest
          find . -name "*.pyc" -delete
          find . -name "__pycache__" -delete
          # Ejecutamos asegurando que SOLO vea esta carpeta
          PYTHONPATH=. python -m pytest test_main.py -v
